// this file is auto-generated by the specmatic gradle plugin. Any changes will be lost!
package io.specmatic.release.test.list

object VersionInfo {
    val version = "unspecified"
    val gitCommit = "unknown - no git repo found"
    val gitShortCommit = "unknown"
    val group = "io.specmatic.release-test"
    val name = "list"
    
    
    fun describe() = "vunspecified"
}