// this file is auto-generated by the specmatic gradle plugin. Any changes will be lost!
package io.specmatic.release.test.app

import org.slf4j.bridge.SLF4JBridgeHandler
import java.util.logging.LogManager

object JULForwarder {
    fun forward() {
        LogManager.getLogManager().reset()
        SLF4JBridgeHandler.removeHandlersForRootLogger()
        SLF4JBridgeHandler.install()
    }
}